#Makes the impaling enchantment apply to any creature in contact with rain or water.
#Default Value: true
#Requires Restart: Game
boost_impaling = true
#Tridents can be repaired in an anvil using prismarine shards.
#Default Value: true
repair_tridents = true
